### ISSUE TITLE
Destructing a marker results in error

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/tools-page#194]
Switch from one tool to another on tools page and then to the third tool before the second one loads
(double click a card at the bottom like a boomer)

error: `Cannot read property 'keys' of undefined at findConceptForSpace`

![image](https://user-images.githubusercontent.com/3648190/113170728-1d7d0d00-9247-11eb-8c0e-f1b2b52c23eb.png)

resolveRef(this.config.data): 
`ref: {transform: "entityConceptSkipFilter", model: "markers.mountain.encoding.color"}`

transformModel(): 
`model.data.config = concept: "world_4region" space: ["country"]`

findConceptForSpace()
`const filteredConcepts =  [...availability.keyValueLookup.get(createKeyStr(space)).keys()]`

space = ["country"]
availability.keyValueLookup = Map(0)

**Comment by jheeffer** [comment]
Probably fixed with https://github.com/vizabi/vizabi-reactive/commit/35346b93e9a19fed223efcad65fa070530ba2da2 and https://github.com/vizabi/vizabi-shared-components/commit/c85f914db099b5598d8a5180c6b9c0b21235104b

You can probably safely remove the call to marker.destruct from tool code to clean it up.
