### ISSUE TITLE
Taiwan not listed as separate entity from China

### ISSUE THREAD

**Issue by timbolimbo222** [Gapminder/tools-page#247]
Taiwan, apart from a shared culture rooted in Han Chinese tradition and some folk tradition from the coastal provinces of China, is very, very different from China, both socially and economically. Data discreet to Taiwan is freely available (unlike China), and I am quite surprised that an institution such as Gapminder has taken the position of lumping Taiwan in with China, as it seems to have done at least regarding the dataset for income levels on this page: https://www.gapminder.org/tools/#$chart-type=bubbles&url=v1

I notice that Taiwan also does not seem to be included in the Gapminder Offline tool. Please consider your apparently overarching mission statement, which I believe is something along the lines of correcting misconceptions. Taiwan is different from China. Though significantly entangled with one another, the two entities are worlds apart. Taiwan is a vibrant democracy with a free press and one of the most progressive societies in Asia, having left the oppressive principles of one-party leadership behind almost 30 years ago. China is an aggressively repressive regime that has engaged in genocide since the communist takeover in 1949, and continues to do so today with the Uyghur population. Wake up, Gapminder.

**Comment by angieskazka** [comment]
Hej @timbolimbo222, i just woke up

Thanks for pointing this out. By this logic we should also not include Åland into Finland, Greendland into Danmark, Florida into USA, Crimea into whatever it is being part of now... Kashmir, Tibet, HK, Macao etc. There are many territories that are disputed and situations around them are complicated and politically charged. So the definition of a "country" is not easy.

Our mission statement also says that Gapminder is an independent organisation, free from political alignments. Showing Taiwan separately would mean we are taking a side, which we shouldn't (though i personally may hold a different opinion :)

So for now our policy is the following: show the [UN states](https://en.wikipedia.org/wiki/Member_states_of_the_United_Nations). Because that list has a clear definition and is agreed upon all parties. 

There are two ways Taiwan can appear on the charts: either Taiwan gets a seat at the UN. Or... and this is our plan for the future: we will transition to the chart showing places and not countries/UN states. So you would be able to see a place China and a place Taiwan. And places like Florida or Mumbai, whatever the data has available.

I know this is probably not very helpful, but at least you know why Taiwan is missing from the chart
//Angie
